program loop_test_simplified
    use iso_fortran_env, only : real32, real64
    use parameters
    use read_field_config
    use lattice
    use thermal_lines
    implicit none

    character(len=512) :: gauge_filename
    integer :: argument_count
    integer :: x, y, z, mu, site
    integer :: blocking_level, loop_number
    integer :: in_site, out_site
    complex(real32), allocatable :: gauge_field_raw(:,:,:,:,:,:,:)
    complex(real64), allocatable :: gauge_field_slice(:,:,:,:)
    complex(real64), allocatable :: gauge_field_blocked(:,:,:,:,:)
    complex(real64), allocatable :: A11(:,:)

    call initialise_parameters('parameter_file.txt')
    call setup_lattice()

    argument_count = command_argument_count()
    if (argument_count >= 1) then
        call get_command_argument(1, gauge_filename)
    else
        gauge_filename = '../fortran77_scalar_looptest/run1_52x26x26x26nc2rADJnf2b2.300000m1.000000n1'
    endif

    allocate(gauge_field_raw(NCOL, NCOL, LX1, LX2, LX3, LX4, 4))
    allocate(gauge_field_slice(NCOL, NCOL, SLICE_VOLUME, 3))
    allocate(gauge_field_blocked(NCOL, NCOL, SLICE_VOLUME, 3, MAX_BLOCKING_LEVEL))
    allocate(A11(NCOL, NCOL))

    call read_gauge_field(trim(gauge_filename), gauge_field_raw)

    do mu = 1, 3
        do z = 1, LX3
            do y = 1, LX2
                do x = 1, LX1
                    site = site_index(x, y, z)
                    gauge_field_slice(:,:,site,mu) = cmplx( &
                        real(gauge_field_raw(:,:,x,y,z,1,mu), kind=real64), &
                        real(aimag(gauge_field_raw(:,:,x,y,z,1,mu)), kind=real64), &
                        kind=real64 &
                    )
                enddo
            enddo
        enddo
    enddo

    gauge_field_blocked = get_blocked_gauge_field(gauge_field_slice)

    call get_square_pulses(gauge_field_blocked, 1)
    call get_plaquettes(gauge_field_blocked, 1)

    open(unit=77, file='new_loop_outputs.dat', status='replace', action='write')
    write(77,'(A)') 'New-code loop-by-loop A11 matrices'

    in_site = site_index(1, 1, 1)

    do blocking_level = 1, MAX_BLOCKING_LEVEL
        do loop_number = 1, 144
            call identity_matrix(A11)
            call call_loop(loop_number, in_site, out_site, A11, blocking_level, gauge_field_blocked)
            call dump_A11(77, 1, blocking_level, loop_number, in_site, out_site, A11)
        enddo
    enddo

    close(77)

contains

    subroutine identity_matrix(matrix)
        complex(real64), intent(out) :: matrix(:,:)
        integer :: colour_index

        matrix = cmplx(0.0_real64, 0.0_real64, kind=real64)
        do colour_index = 1, size(matrix, 1)
            matrix(colour_index, colour_index) = cmplx(1.0_real64, 0.0_real64, kind=real64)
        enddo
    end subroutine identity_matrix

    subroutine dump_A11(unit_number, time_slice, blocking_level, loop_number, in_site, out_site, A11)
        integer, intent(in) :: unit_number, time_slice, blocking_level, loop_number, in_site, out_site
        complex(real64), intent(in) :: A11(:,:)

        write(unit_number,'(A)') '----------------------------------------'
        write(unit_number,'(A,I0)') 'Loop ', loop_number
        write(unit_number,900) time_slice, blocking_level, in_site, out_site
        write(unit_number,'(A)') 'A11 ='
        write(unit_number,901) real(A11(1,1)), aimag(A11(1,1)), real(A11(1,2)), aimag(A11(1,2))
        write(unit_number,901) real(A11(2,1)), aimag(A11(2,1)), real(A11(2,2)), aimag(A11(2,2))
        write(unit_number,*)
900     format('N4=',I0,'  IBL=',I0,'  MN=',I0,'  OUT_SITE=',I0)
901     format('(',ES16.8,',',ES16.8,')  (',ES16.8,',',ES16.8,')')
    end subroutine dump_A11

    subroutine call_loop(loop_number, in_site, out_site, A11, blocking_level, gauge_field_blocked)
        integer, intent(in) :: loop_number, in_site, blocking_level
        integer, intent(out) :: out_site
        complex(real64), intent(inout) :: A11(NCOL, NCOL)
        complex(real64), intent(in) :: gauge_field_blocked(NCOL, NCOL, SLICE_VOLUME, 3, MAX_BLOCKING_LEVEL)

        select case(loop_number)
        case(1)
            call loop_1(in_site, out_site, A11, blocking_level)
        case(2)
            call loop_2(in_site, out_site, A11, blocking_level)
        case(3)
            call loop_3(in_site, out_site, A11, blocking_level)
        case(4)
            call loop_4(in_site, out_site, A11, blocking_level)
        case(5)
            call loop_5(in_site, out_site, A11, blocking_level)
        case(6)
            call loop_6(in_site, out_site, A11, blocking_level)
        case(7)
            call loop_7(in_site, out_site, A11, blocking_level)
        case(8)
            call loop_8(in_site, out_site, A11, blocking_level)
        case(9)
            call loop_9(in_site, out_site, A11, blocking_level)
        case(10)
            call loop_10(in_site, out_site, A11, blocking_level)
        case(11)
            call loop_11(in_site, out_site, A11, blocking_level)
        case(12)
            call loop_12(in_site, out_site, A11, blocking_level)
        case(13)
            call loop_13(in_site, out_site, A11, blocking_level)
        case(14)
            call loop_14(in_site, out_site, A11, blocking_level)
        case(15)
            call loop_15(in_site, out_site, A11, blocking_level)
        case(16)
            call loop_16(in_site, out_site, A11, blocking_level)
        case(17)
            call loop_17(in_site, out_site, A11, blocking_level)
        case(18)
            call loop_18(in_site, out_site, A11, blocking_level)
        case(19)
            call loop_19(in_site, out_site, A11, blocking_level)
        case(20)
            call loop_20(in_site, out_site, A11, blocking_level)
        case(21)
            call loop_21(in_site, out_site, A11, blocking_level)
        case(22)
            call loop_22(in_site, out_site, A11, blocking_level)
        case(23)
            call loop_23(in_site, out_site, A11, blocking_level)
        case(24)
            call loop_24(in_site, out_site, A11, blocking_level)
        case(25)
            call loop_25(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(26)
            call loop_26(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(27)
            call loop_27(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(28)
            call loop_28(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(29)
            call loop_29(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(30)
            call loop_30(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(31)
            call loop_31(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(32)
            call loop_32(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(33)
            call loop_33(in_site, out_site, A11, blocking_level)
        case(34)
            call loop_34(in_site, out_site, A11, blocking_level)
        case(35)
            call loop_35(in_site, out_site, A11, blocking_level)
        case(36)
            call loop_36(in_site, out_site, A11, blocking_level)
        case(37)
            call loop_37(in_site, out_site, A11, blocking_level)
        case(38)
            call loop_38(in_site, out_site, A11, blocking_level)
        case(39)
            call loop_39(in_site, out_site, A11, blocking_level)
        case(40)
            call loop_40(in_site, out_site, A11, blocking_level)
        case(41)
            call loop_41(in_site, out_site, A11, blocking_level)
        case(42)
            call loop_42(in_site, out_site, A11, blocking_level)
        case(43)
            call loop_43(in_site, out_site, A11, blocking_level)
        case(44)
            call loop_44(in_site, out_site, A11, blocking_level)
        case(45)
            call loop_45(in_site, out_site, A11, blocking_level)
        case(46)
            call loop_46(in_site, out_site, A11, blocking_level)
        case(47)
            call loop_47(in_site, out_site, A11, blocking_level)
        case(48)
            call loop_48(in_site, out_site, A11, blocking_level)
        case(49)
            call loop_49(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(50)
            call loop_50(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(51)
            call loop_51(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(52)
            call loop_52(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(53)
            call loop_53(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(54)
            call loop_54(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(55)
            call loop_55(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(56)
            call loop_56(in_site, out_site, A11, blocking_level, gauge_field_blocked)
        case(57)
            call loop_57(in_site, out_site, A11, blocking_level)
        case(58)
            call loop_58(in_site, out_site, A11, blocking_level)
        case(59)
            call loop_59(in_site, out_site, A11, blocking_level)
        case(60)
            call loop_60(in_site, out_site, A11, blocking_level)
        case(61)
            call loop_61(in_site, out_site, A11, blocking_level)
        case(62)
            call loop_62(in_site, out_site, A11, blocking_level)
        case(63)
            call loop_63(in_site, out_site, A11, blocking_level)
        case(64)
            call loop_64(in_site, out_site, A11, blocking_level)
        case(65)
            call loop_65(in_site, out_site, A11, blocking_level)
        case(66)
            call loop_66(in_site, out_site, A11, blocking_level)
        case(67)
            call loop_67(in_site, out_site, A11, blocking_level)
        case(68)
            call loop_68(in_site, out_site, A11, blocking_level)
        case(69)
            call loop_69(in_site, out_site, A11, blocking_level)
        case(70)
            call loop_70(in_site, out_site, A11, blocking_level)
        case(71)
            call loop_71(in_site, out_site, A11, blocking_level)
        case(72)
            call loop_72(in_site, out_site, A11, blocking_level)
        case(73)
            call loop_73(in_site, out_site, A11, blocking_level)
        case(74)
            call loop_74(in_site, out_site, A11, blocking_level)
        case(75)
            call loop_75(in_site, out_site, A11, blocking_level)
        case(76)
            call loop_76(in_site, out_site, A11, blocking_level)
        case(77)
            call loop_77(in_site, out_site, A11, blocking_level)
        case(78)
            call loop_78(in_site, out_site, A11, blocking_level)
        case(79)
            call loop_79(in_site, out_site, A11, blocking_level)
        case(80)
            call loop_80(in_site, out_site, A11, blocking_level)
        case(81)
            call loop_81(in_site, out_site, A11, blocking_level)
        case(82)
            call loop_82(in_site, out_site, A11, blocking_level)
        case(83)
            call loop_83(in_site, out_site, A11, blocking_level)
        case(84)
            call loop_84(in_site, out_site, A11, blocking_level)
        case(85)
            call loop_85(in_site, out_site, A11, blocking_level)
        case(86)
            call loop_86(in_site, out_site, A11, blocking_level)
        case(87)
            call loop_87(in_site, out_site, A11, blocking_level)
        case(88)
            call loop_88(in_site, out_site, A11, blocking_level)
        case(89)
            call loop_89(in_site, out_site, A11, blocking_level)
        case(90)
            call loop_90(in_site, out_site, A11, blocking_level)
        case(91)
            call loop_91(in_site, out_site, A11, blocking_level)
        case(92)
            call loop_92(in_site, out_site, A11, blocking_level)
        case(93)
            call loop_93(in_site, out_site, A11, blocking_level)
        case(94)
            call loop_94(in_site, out_site, A11, blocking_level)
        case(95)
            call loop_95(in_site, out_site, A11, blocking_level)
        case(96)
            call loop_96(in_site, out_site, A11, blocking_level)
        case(97)
            call loop_97(in_site, out_site, A11, blocking_level)
        case(98)
            call loop_98(in_site, out_site, A11, blocking_level)
        case(99)
            call loop_99(in_site, out_site, A11, blocking_level)
        case(100)
            call loop_100(in_site, out_site, A11, blocking_level)
        case(101)
            call loop_101(in_site, out_site, A11, blocking_level)
        case(102)
            call loop_102(in_site, out_site, A11, blocking_level)
        case(103)
            call loop_103(in_site, out_site, A11, blocking_level)
        case(104)
            call loop_104(in_site, out_site, A11, blocking_level)
        case(105)
            call loop_105(in_site, out_site, A11, blocking_level)
        case(106)
            call loop_106(in_site, out_site, A11, blocking_level)
        case(107)
            call loop_107(in_site, out_site, A11, blocking_level)
        case(108)
            call loop_108(in_site, out_site, A11, blocking_level)
        case(109)
            call loop_109(in_site, out_site, A11, blocking_level)
        case(110)
            call loop_110(in_site, out_site, A11, blocking_level)
        case(111)
            call loop_111(in_site, out_site, A11, blocking_level)
        case(112)
            call loop_112(in_site, out_site, A11, blocking_level)
        case(113)
            call loop_113(in_site, out_site, A11, blocking_level)
        case(114)
            call loop_114(in_site, out_site, A11, blocking_level)
        case(115)
            call loop_115(in_site, out_site, A11, blocking_level)
        case(116)
            call loop_116(in_site, out_site, A11, blocking_level)
        case(117)
            call loop_117(in_site, out_site, A11, blocking_level)
        case(118)
            call loop_118(in_site, out_site, A11, blocking_level)
        case(119)
            call loop_119(in_site, out_site, A11, blocking_level)
        case(120)
            call loop_120(in_site, out_site, A11, blocking_level)
        case(121)
            call loop_121(in_site, out_site, A11, blocking_level)
        case(122)
            call loop_122(in_site, out_site, A11, blocking_level)
        case(123)
            call loop_123(in_site, out_site, A11, blocking_level)
        case(124)
            call loop_124(in_site, out_site, A11, blocking_level)
        case(125)
            call loop_125(in_site, out_site, A11, blocking_level)
        case(126)
            call loop_126(in_site, out_site, A11, blocking_level)
        case(127)
            call loop_127(in_site, out_site, A11, blocking_level)
        case(128)
            call loop_128(in_site, out_site, A11, blocking_level)
        case(129)
            call loop_129(in_site, out_site, A11, blocking_level)
        case(130)
            call loop_130(in_site, out_site, A11, blocking_level)
        case(131)
            call loop_131(in_site, out_site, A11, blocking_level)
        case(132)
            call loop_132(in_site, out_site, A11, blocking_level)
        case(133)
            call loop_133(in_site, out_site, A11, blocking_level)
        case(134)
            call loop_134(in_site, out_site, A11, blocking_level)
        case(135)
            call loop_135(in_site, out_site, A11, blocking_level)
        case(136)
            call loop_136(in_site, out_site, A11, blocking_level)
        case(137)
            call loop_137(in_site, out_site, A11, blocking_level)
        case(138)
            call loop_138(in_site, out_site, A11, blocking_level)
        case(139)
            call loop_139(in_site, out_site, A11, blocking_level)
        case(140)
            call loop_140(in_site, out_site, A11, blocking_level)
        case(141)
            call loop_141(in_site, out_site, A11, blocking_level)
        case(142)
            call loop_142(in_site, out_site, A11, blocking_level)
        case(143)
            call loop_143(in_site, out_site, A11, blocking_level)
        case(144)
            call loop_144(in_site, out_site, A11, blocking_level)
        case default
            error stop 'Invalid loop number in call_loop'
        end select
    end subroutine call_loop
end program loop_test_simplified
